# Generated by Django 6.0.4 on 2026-04-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
